import { User } from "./User"
export const USER: User[] = [
    {
        id: 1,
        fname: 'Clothes',
        lname: 'Me',
        uname: 'The Clothes',
        password: '12345678',
        email: 'example@gmail.com',
        country: 'Philippines',
        city: 'Baguio',
    },
    {
        id: 2,
        fname: 'Clothes',
        lname: 'Me',
        uname: 'The Clothes',
        password: '12345678',
        email: 'example@gmail.com',
        country: 'Philippines',
        city: 'Baguio',
    },
    {
        id: 3,
        fname: 'Clothes',
        lname: 'Me',
        uname: 'The Clothes',
        password: '12345678',
        email: 'example@gmail.com',
        country: 'Philippines',
        city: 'Baguio',
    },
    {
        id: 4,
        fname: 'Clothes',
        lname: 'Me',
        uname: 'The Clothes',
        password: '12345678',
        email: 'example@gmail.com',
        country: 'Philippines',
        city: 'Baguio',
    },
    {
        id: 5,
        fname: 'Clothes',
        lname: 'Me',
        uname: 'The Clothes',
        password: '12345678',
        email: 'example@gmail.com',
        country: 'Philippines',
        city: 'Baguio',
    },
];