import { User } from "./User"
export const USER: User[] = [
    {
        id: 1,
        fname: 'Brakhen Jules',
        lname: 'Soriano',
        uname: 'Brakhen Jules Soriano',
        password: '12345678',
        email: 'example@gmail.com',
        country: 'Philippines',
        city: 'Baguio',
    },
    {
        id: 2,
        fname: 'Bailu',
        lname: 'Bronya',
        uname: 'Bailu Bronya',
        password: '12345678',
        email: 'example@gmail.com',
        country: 'Philippines',
        city: 'Baguio',
    },
    {
        id: 3,
        fname: 'Clara',
        lname: 'Hemiko',
        uname: 'Clara Hemiko',
        password: '12345678',
        email: 'example@gmail.com',
        country: 'Philippines',
        city: 'Baguio',
    },
    {
        id: 4,
        fname: 'Fu',
        lname: 'Xuan',
        uname: 'Fu Xuan',
        password: '12345678',
        email: 'example@gmail.com',
        country: 'Philippines',
        city: 'Baguio',
    },
    {
        id: 5,
        fname: 'Herta',
        lname: 'Hook',
        uname: 'Herta Hook',
        password: '12345678',
        email: 'example@gmail.com',
        country: 'Philippines',
        city: 'Baguio',
    },
];